var AppConstants = {
  DISPLAY_SIGN_IN: "DISPLAY_SIGN_IN",
  DISPLAY_SIGN_UP: "DISPLAY_SIGN_UP",
  DISPLAY_ERRORS: "DISPLAY_ERRORS",
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  DISPLAY_TRAILER_MODAL: "DISPLAY_TRAILER_MODAL"
};

module.exports = AppConstants;
