var MovieConstants = {
  SINGLE_MOVIE_RECEIVED: "SINGLE_MOVIE_RECEIVED",
  HOME_PAGE_MOVIES_RECEIVED: "HOME_PAGE_MOVIES_RECEIVED",
  CLEAR_CURRENT_MOVIE: "CLEAR_CURRENT_MOVIE"
};

module.exports = MovieConstants;
